# Generated by Django 5.2.5 on 2025-09-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category'),
        ),
        migrations.AddIndex(
            model_name='fixturerevision',
            index=models.Index(fields=['fixture_slug'], name='django_fixt_fixture_5760c0_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturerevision',
            index=models.Index(fields=['fixture_slug', 'revision'], name='django_fixt_fixture_2f30d0_idx'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this image', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'activity_type'], name='activity_lo_user_id_297468_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['image_type'], name='core_images_image_t_e2dc20_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['uploaded_by'], name='core_images_uploade_55bad0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['created_at'], name='core_images_created_afccab_idx'),
        ),
    ]
